"""Stage 6: Assembly & Export — combine all chapters into final manuscript."""

import logging
from datetime import datetime
from rich.console import Console

from sovereign_ink.pipeline.base import PipelineStage

logger = logging.getLogger(__name__)
console = Console()


class AssemblyExportStage(PipelineStage):
    STAGE_NAME = "assembly_export"

    def check_prerequisites(self) -> bool:
        latest = self.state_manager.get_latest_draft_version()
        return latest is not None

    def run(self) -> None:
        self._mark_started()

        try:
            novel_spec = self.state_manager.load_novel_spec()
            structure = self.state_manager.load_novel_structure()

            # Use the latest version of chapters (after all revision passes)
            latest_version = self.state_manager.get_latest_draft_version()
            console.print(
                f"\n[bold cyan]Assembling manuscript from "
                f"{latest_version}...[/bold cyan]"
            )

            chapters = self.state_manager.load_all_chapter_drafts(latest_version)

            if not chapters:
                raise RuntimeError("No chapter drafts found to assemble")

            # Build front matter
            title = (
                novel_spec.title
                if novel_spec and novel_spec.title
                else "Untitled Novel"
            )

            manuscript_parts: list[str] = []

            # Title page
            manuscript_parts.append(f"# {title}\n")
            if novel_spec:
                manuscript_parts.append(
                    f"*A novel set in {novel_spec.region}, "
                    f"{novel_spec.era_start}–{novel_spec.era_end}*\n"
                )
                manuscript_parts.append("*Generated by Sovereign Ink*\n")
            manuscript_parts.append("---\n")

            # Table of contents
            manuscript_parts.append("## Table of Contents\n")
            for ch_num in sorted(chapters.keys()):
                ch_title = f"Chapter {ch_num}"
                if structure:
                    for co in structure.chapter_outlines:
                        if co.chapter_number == ch_num:
                            ch_title = f"Chapter {ch_num}: {co.title}"
                            break
                manuscript_parts.append(f"- {ch_title}")
            manuscript_parts.append("\n---\n")

            # Chapters
            total_words = 0
            for ch_num in sorted(chapters.keys()):
                content = chapters[ch_num]
                word_count = len(content.split())
                total_words += word_count

                manuscript_parts.append(f"\n{content}\n")
                manuscript_parts.append("---\n")

            full_manuscript = "\n".join(manuscript_parts)

            # Save manuscript
            self.state_manager.save_manuscript(full_manuscript)

            # Save individual chapter files to output/
            for ch_num in sorted(chapters.keys()):
                content = chapters[ch_num]
                self.state_manager.save_chapter_draft(ch_num, content, "output")

            # Generate metadata
            metadata = {
                "title": title,
                "region": novel_spec.region if novel_spec else "Unknown",
                "era": (
                    f"{novel_spec.era_start}-{novel_spec.era_end}"
                    if novel_spec
                    else "Unknown"
                ),
                "total_word_count": total_words,
                "chapter_count": len(chapters),
                "source_version": latest_version,
                "generated_at": datetime.now().isoformat(),
                "total_tokens_used": self.pipeline_state.total_tokens_used,
                "total_cost_estimate": (
                    f"${self.pipeline_state.total_cost_estimate:.4f}"
                ),
                "chapter_word_counts": {
                    str(ch_num): len(content.split())
                    for ch_num, content in sorted(chapters.items())
                },
            }
            self.state_manager.save_metadata(metadata)

            console.print("\n[bold green]Manuscript assembled![/bold green]")
            console.print(f"  Total words: {total_words:,}")
            console.print(f"  Chapters: {len(chapters)}")
            console.print(
                f"  Output: "
                f"{self.state_manager.project_dir / 'output' / 'manuscript.md'}"
            )

            self._mark_completed()

        except Exception as e:
            self._mark_failed(str(e))
            raise
